// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://scwhurqvgeskseugwcrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjd2h1cnF2Z2Vza3NldWd3Y3J4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MzM5ODcsImV4cCI6MjA3NDUwOTk4N30.l6-4WrBsr3EkjHO7s1XEbQKhgrujdemgIKXLyM4XBbU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});